=== trange1/elektronika/электроника/Mathcad v14.0/Mathcad/program files/Mathcad/Mathcad 14/schema/unitsystem30.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Mike Lippert (Mathsoft) -->
<xs:schema xmlns="http://schemas.mathsoft.com/unit-system30" xmlns:us="http://schemas.mathsoft.com/unit-system30" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://schemas.mathsoft.com/unit-system30" elementFormDefault="qualified" attributeFormDefault="unqualified" version="3.0.0">
	<xs:annotation>
		<xs:documentation xml:lang="en">
			<h1>Mathsoft Mathcad 13.1 Unit System Schema</h1>
			<p>Currently this schema is for internal use only.</p>
			<hr/>
			<pre>
  $Workfile:: UnitSystem30.xsd                                           $
  $Revision:: 1                                                          $
    $Author:: mlippert                                                   $
      $Date:: 2005-09-26 20:58:14-04:00                                  $
$NoKeywords::                                                            $
			</pre>
		</xs:documentation>
	</xs:annotation>
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="W3C-CopyOf-xml.xsd">
		<xs:annotation>
			<xs:documentation>
		       Get access to the xml: attribute groups such as xml:lang and xml:space
			</xs:documentation>
		</xs:annotation>
	</xs:import>
	<xs:element name="unitSystem">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="quantities">
					<xs:annotation>
						<xs:documentation>Collection of quantities known by this unit system</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="quantity">
								<xs:annotation>
									<xs:documentation>Named property ascribed to phenomena, bodies, or substances that can be quantified for, or assigned to, a particular phenomenon, body, or substance. Examples are mass and electric charge.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Description used to help understand the quantity</xs:documentation>
											</xs:annotation>
											<xs:complexType mixed="true">
												<xs:attribute ref="xml:lang" use="optional" default="en"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="displayName" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Displayable description of quantity (language specific)</xs:documentation>
											</xs:annotation>
											<xs:complexType mixed="true">
												<xs:attribute ref="xml:lang" use="optional" default="en"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation xml:lang="en">Unique name for this quantity.</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="base-quantity" type="xs:boolean" default="false">
										<xs:annotation>
											<xs:documentation xml:lang="en">The quantity is a base quantity if it is one of the orthogonal quantities that defines the unit system. All other quantities are derived quantities (ie derived from the base quantities)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="default-unit" type="xs:string">
										<xs:annotation>
											<xs:documentation xml:lang="en">A quantity has a default-unit if it is desired that results that can be simplified to this quantity use this particular unit (which must belong to the quantity) rather than a monomial expression of base quantity units.
Base quantities MUST have a default unit (although the schema doesn't enforce this).
</xs:documentation>
										</xs:annotation>
									</xs:attribute>
								</xs:complexType>
								<!--xs:unique name="UniqueCanonicalQuantityName">
									<xs:selector xpath="."/>
									<xs:field xpath="@name"/>
								</xs:unique-->
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="units">
					<xs:annotation>
						<xs:documentation>Collection of units known by this unit system</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence minOccurs="0" maxOccurs="unbounded">
							<xs:element name="unit">
								<xs:annotation>
									<xs:documentation>Named amount of a quantity</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="description" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Description to help understand the unit</xs:documentation>
											</xs:annotation>
											<xs:complexType mixed="true">
												<xs:attribute ref="xml:lang" use="optional" default="en"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="symbol" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation source="general" xml:lang="en">English Symbol used to denote this unit in an equation. The 1st symbol is the "primary" symbol.</xs:documentation>
												<xs:documentation source="uniqueness" xml:lang="en">A symbol must be unique among the group of all unit's symbols for a given language.</xs:documentation>
												<xs:documentation source="primary symbol definition" xml:lang="en">When there is more than one symbol for a unit, the 1st symbol is considered the primary symbol. The primary symbol is the one that will be used by default to represent the unit.</xs:documentation>
											</xs:annotation>
											<xs:complexType mixed="false">
												<xs:sequence minOccurs="0" maxOccurs="unbounded">
													<xs:element name="localSymbol">
														<xs:annotation>
															<xs:documentation>Translation of the english symbol for another language</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:attribute name="name" type="xs:string" use="required"/>
															<xs:attribute ref="xml:lang" use="required"/>
														</xs:complexType>
														<!--xs:unique name="UniqueUnitSymbolTranslation">
															<xs:selector xpath="."/>
															<xs:field xpath="@xml:lang"/>
														</xs:unique-->
													</xs:element>
												</xs:sequence>
												<xs:attribute name="name" type="xs:string" use="required"/>
												<xs:attribute ref="xml:lang" use="optional" fixed="en"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="displayName" maxOccurs="unbounded">
											<xs:annotation>
												<xs:documentation>Displayable description of unit (language specific)</xs:documentation>
											</xs:annotation>
											<xs:complexType mixed="true">
												<xs:attribute ref="xml:lang" use="optional" default="en"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation xml:lang="en">Unique name for this unit</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="quantity-name" type="xs:string" use="required">
										<xs:annotation>
											<xs:documentation xml:lang="en">Reference to the quantity (sometimes known as a dimension) that this unit is a member of (ie length, time, acceleration etc.)</xs:documentation>
										</xs:annotation>
									</xs:attribute>
									<xs:attribute name="type" default="multiplicative">
										<xs:annotation>
											<xs:documentation xml:lang="en">Multiplicative units are those which follow the rules of multiplication and division, using commutative math, and can be combined and reduced to other kinds of units. 
Scaling units are those which apply a non-multiplicative function of a single variable to a result such as the linear transformations necessary for the Celcius temperature scale. </xs:documentation>
											<xs:documentation xml:lang="en">This is more descriptive than the summary in the 1st doc annotation.
There are two kinds of units in Mathcad: multiplicative, and scaling.  Both kinds of units are really ways of scaling the result, but multiplicative units are those which follow the rules of multiplication and division, using commutative math, and can be combined and reduced to other kinds of units. The unit placeholder will automatically invert the operation when a multiplicative unit is used, dividing the result of an expression by that unit, and displaying the scaled result along with the unit name in the placeholder.  Further, custom unit system settings allow the user to reduce results in terms of any multiplicative unit by default. 
Scaling units, by contrast, are those which apply a non-multiplicative function of a single variable to a result.  Scaling units are nevertheless an accepted engineering concept, such as the linear transformations necessary for Celcius temperature scale. The "forward" scaling unit function can be a function of several variables, to ease input, such as in the case of degrees, minutes, seconds, or polar notation for complex numbers. The "reverse" function must be a function of a single variable, and can never be selected as the default unit, because it cannot be incorporated into the multiplicative linear algebra routines that determine our unit reductions. The user must supple the "reverse" function, because many scaling units don't have mathematically defined "inverses", so Mathcad cannot create one automatically.</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="multiplicative"/>
												<xs:enumeration value="scaling"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
								<!--xs:unique name="UniqueCanonicalUnitName">
									<xs:selector xpath="."/>
									<xs:field xpath="@name"/>
								</xs:unique-->
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
		<xs:key name="quantityNameKey">
			<xs:selector xpath="us:quantities/us:quantity"/>
			<xs:field xpath="@name"/>
		</xs:key>
		<xs:key name="unitNameKey">
			<xs:selector xpath="us:units/us:unit"/>
			<xs:field xpath="@name"/>
		</xs:key>
	</xs:element>
</xs:schema>

=== trange1/elektronika/электроника/Mathcad v14.0/Mathcad/program files/Mathcad/Mathcad 14/units/unit-system-None.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	This file provides the list of quantities and units when the selected
	unit system is None. It has no quantities and no units.
-->
<unitSystem name="None"
            xsi:schemaLocation="http://schemas.mathsoft.com/unit-system30
                                ../schema/UnitSystem30.xsd"
            xmlns="http://schemas.mathsoft.com/unit-system30"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<quantities>
		<quantity name="M" base-quantity="true" default-unit="M">
			<displayName xml:lang="en">Mass</displayName>
			<displayName xml:lang="ja">質量</displayName>
			<displayName xml:lang="de">Masse</displayName>
			<displayName xml:lang="fr">Masse</displayName>
			<displayName xml:lang="ko">질량</displayName>
			<displayName xml:lang="zh-Hant">質量</displayName>
			<displayName xml:lang="es">Masa</displayName>
			<displayName xml:lang="zh-Hans">质量</displayName>
			<displayName xml:lang="it">Massa</displayName>
		</quantity>
		<quantity name="L" base-quantity="true" default-unit="L">
			<displayName xml:lang="en">Length</displayName>
			<displayName xml:lang="ja">長さ</displayName>
			<displayName xml:lang="de">Länge</displayName>
			<displayName xml:lang="fr">Longueur</displayName>
			<displayName xml:lang="ko">길이</displayName>
			<displayName xml:lang="zh-Hant">長度</displayName>
			<displayName xml:lang="es">Longitud</displayName>
			<displayName xml:lang="zh-Hans">长度</displayName>
			<displayName xml:lang="it">Lunghezza</displayName>
		</quantity>
		<quantity name="T" base-quantity="true" default-unit="T">
			<displayName xml:lang="en">Time</displayName>
			<displayName xml:lang="ja">時間 (または時刻)</displayName>
			<displayName xml:lang="de">Zeit</displayName>
			<displayName xml:lang="fr">Temps</displayName>
			<displayName xml:lang="ko">시(시간)</displayName>
			<displayName xml:lang="zh-Hant">時間</displayName>
			<displayName xml:lang="es">Tiempo</displayName>
			<displayName xml:lang="zh-Hans">单位时间</displayName>
			<displayName xml:lang="it">Tempo</displayName>
		</quantity>
		<quantity name="Q" base-quantity="true" default-unit="Q">
			<displayName xml:lang="en">Current</displayName>
			<displayName xml:lang="ja">電流</displayName>
			<displayName xml:lang="de">Strom</displayName>
			<displayName xml:lang="fr">Courant</displayName>
			<displayName xml:lang="ko">전류</displayName>
			<displayName xml:lang="zh-Hant">電流</displayName>
			<displayName xml:lang="es">Corriente</displayName>
			<displayName xml:lang="zh-Hans">电流</displayName>
			<displayName xml:lang="it">Corrente</displayName>
		</quantity>
		<quantity name="K" base-quantity="true" default-unit="K">
			<displayName xml:lang="en">Temperature</displayName>
			<displayName xml:lang="ja">温度</displayName>
			<displayName xml:lang="de">Temperatur</displayName>
			<displayName xml:lang="fr">Température</displayName>
			<displayName xml:lang="ko">온도</displayName>
			<displayName xml:lang="zh-Hant">溫度</displayName>
			<displayName xml:lang="es">Temperatura</displayName>
			<displayName xml:lang="zh-Hans">温度</displayName>
			<displayName xml:lang="it">Temperatura</displayName>
		</quantity>
		<quantity name="C" base-quantity="true" default-unit="C">
			<displayName xml:lang="en">Luminous Intensity</displayName>
			<displayName xml:lang="ja">光度</displayName>
			<displayName xml:lang="de">Lichtstärke</displayName>
			<displayName xml:lang="fr">Intensité lumineuse</displayName>
			<displayName xml:lang="ko">광도</displayName>
			<displayName xml:lang="zh-Hant">發光強度</displayName>
			<displayName xml:lang="es">Intensidad luminosa</displayName>
			<displayName xml:lang="zh-Hans">发光强度</displayName>
			<displayName xml:lang="it">Intensità luminosa</displayName>
		</quantity>
		<quantity name="S" base-quantity="true" default-unit="S">
			<displayName xml:lang="en">Substance</displayName>
			<displayName xml:lang="ja">物質量</displayName>
			<displayName xml:lang="de">Stoff</displayName>
			<displayName xml:lang="fr">Substance</displayName>
			<displayName xml:lang="ko">물질</displayName>
			<displayName xml:lang="zh-Hant">物質</displayName>
			<displayName xml:lang="es">Sustancia</displayName>
			<displayName xml:lang="zh-Hans">物质</displayName>
			<displayName xml:lang="it">Sostanza</displayName>
		</quantity>
		<quantity name="D" base-quantity="true" default-unit="D">
			<displayName xml:lang="en">Money</displayName>
			<displayName xml:lang="de">Geld</displayName>
			<displayName xml:lang="fr">Argent</displayName>
			<displayName xml:lang="es">Moneda</displayName>
			<displayName xml:lang="it">Valuta</displayName>
			<displayName xml:lang="ja">通貨</displayName>
			<displayName xml:lang="ko">돈</displayName>
			<displayName xml:lang="zh-Hant">貨幣</displayName>
			<displayName xml:lang="zh-Hans">货币</displayName>
		</quantity>
	</quantities>
	<units>
		<unit name="M" quantity-name="M">
			<symbol name="M" xml:lang="en"/>
			<displayName xml:lang="en">M</displayName>
			<displayName xml:lang="ja">+[M]</displayName>
			<displayName xml:lang="de">M</displayName>
			<displayName xml:lang="fr">M</displayName>
			<displayName xml:lang="ko">M</displayName>
			<displayName xml:lang="zh-Hant">M</displayName>
			<displayName xml:lang="es">M</displayName>
			<displayName xml:lang="zh-Hans">M</displayName>
			<displayName xml:lang="it">M</displayName>
		</unit>
		<unit name="L" quantity-name="L">
			<symbol name="L" xml:lang="en"/>
			<displayName xml:lang="en">L</displayName>
			<displayName xml:lang="ja">L</displayName>
			<displayName xml:lang="de">L</displayName>
			<displayName xml:lang="fr">L</displayName>
			<displayName xml:lang="ko">L</displayName>
			<displayName xml:lang="zh-Hant">L</displayName>
			<displayName xml:lang="es">L</displayName>
			<displayName xml:lang="zh-Hans">L</displayName>
			<displayName xml:lang="it">L</displayName>
		</unit>
		<unit name="T" quantity-name="T">
			<symbol name="T" xml:lang="en"/>
			<displayName xml:lang="en">T</displayName>
			<displayName xml:lang="ja">T</displayName>
			<displayName xml:lang="de">T</displayName>
			<displayName xml:lang="fr">T</displayName>
			<displayName xml:lang="ko">T</displayName>
			<displayName xml:lang="zh-Hant">T</displayName>
			<displayName xml:lang="es">T</displayName>
			<displayName xml:lang="zh-Hans">T</displayName>
			<displayName xml:lang="it">T</displayName>
		</unit>
		<unit name="Q" quantity-name="Q">
			<symbol name="Q" xml:lang="en"/>
			<displayName xml:lang="en">Q</displayName>
			<displayName xml:lang="ja">Q</displayName>
			<displayName xml:lang="de">Q</displayName>
			<displayName xml:lang="fr">Q</displayName>
			<displayName xml:lang="ko">Q</displayName>
			<displayName xml:lang="zh-Hant">Q</displayName>
			<displayName xml:lang="es">Q</displayName>
			<displayName xml:lang="zh-Hans">Q</displayName>
			<displayName xml:lang="it">Q</displayName>
		</unit>
		<unit name="K" quantity-name="K">
			<symbol name="K" xml:lang="en"/>
			<displayName xml:lang="en">K</displayName>
			<displayName xml:lang="ja">K</displayName>
			<displayName xml:lang="de">K</displayName>
			<displayName xml:lang="fr">K</displayName>
			<displayName xml:lang="ko">K</displayName>
			<displayName xml:lang="zh-Hant">K</displayName>
			<displayName xml:lang="es">K</displayName>
			<displayName xml:lang="zh-Hans">K</displayName>
			<displayName xml:lang="it">K</displayName>
		</unit>
		<unit name="C" quantity-name="C">
			<symbol name="C" xml:lang="en"/>
			<displayName xml:lang="en">C</displayName>
			<displayName xml:lang="ja">C</displayName>
			<displayName xml:lang="de">C</displayName>
			<displayName xml:lang="fr">C</displayName>
			<displayName xml:lang="ko">C</displayName>
			<displayName xml:lang="zh-Hant">C</displayName>
			<displayName xml:lang="es">C</displayName>
			<displayName xml:lang="zh-Hans">C</displayName>
			<displayName xml:lang="it">C</displayName>
		</unit>
		<unit name="S" quantity-name="S">
			<symbol name="S" xml:lang="en"/>
			<displayName xml:lang="en">S</displayName>
			<displayName xml:lang="ja">+[S]</displayName>
			<displayName xml:lang="de">S</displayName>
			<displayName xml:lang="fr">S</displayName>
			<displayName xml:lang="ko">S</displayName>
			<displayName xml:lang="zh-Hant">S</displayName>
			<displayName xml:lang="es">S</displayName>
			<displayName xml:lang="zh-Hans">S</displayName>
			<displayName xml:lang="it">S</displayName>
		</unit>
		<unit name="D" quantity-name="D">
			<symbol name="D" xml:lang="en"/>
			<displayName xml:lang="en">D</displayName>
			<displayName xml:lang="de">D</displayName>
			<displayName xml:lang="fr">D</displayName>
			<displayName xml:lang="es">D</displayName>
			<displayName xml:lang="it">D</displayName>
			<displayName xml:lang="ja">D</displayName>
			<displayName xml:lang="ko">D</displayName>
			<displayName xml:lang="zh-Hant">D</displayName>
			<displayName xml:lang="zh-Hans">D</displayName>
		</unit>
	</units>
</unitSystem>
